### ISSUE TITLE
Module not found with Python3

### ISSUE THREAD

**Issue by JonasRigo** [TRIQS/cthyb_matrix#13]
Hi,

I was able to install TRIQS and CTHYB without any problems and I also ran code successfully using python 2.7. But when I use python 3.6 I get the erorr 

ModuleNotFoundError: No module named 'cpp2py_info_base'

When I run the code in the site-packages/cpp2py directory i get this error

ModuleNotFoundError: No module named 'mesh_point'

So, I assume that I miss some path variables, is this true? If so, which are the variables I have to set?

Thanks?

**Comment by HugoStrand** [comment]
Dear @JonasRigo,

This repository is deprecated and only kept for historical reasons. For the TRIQS cthyb solver please have a look at TRIQS/cthyb

https://github.com/TRIQS/cthyb

Best, Hugo
