### ISSUE TITLE
Error when downloading triqs

### ISSUE THREAD

**Issue by BrainsChen** [TRIQS/cthyb_matrix#2]
Could you help me to solve the following problem?

git clone git@github.com:TRIQS/triqs.git .
Cloning into 'triqs'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by parcollet** [comment]
Hi, 
Indeed, there is a little error in the doc : 
the correct address for github is : 
https://github.com/TRIQS/triqs.git
git@ is the ssh access, which requires write permissions.

@mferrero : can you update the doc ... ?

**Comment by BrainsChen** [comment]
So, in the command line of Linux system, how do I download the triqs code?

**Comment by parcollet** [comment]
try
git clone https://github.com/TRIQS/triqs.git
