### ISSUE TITLE
problem in installing triqs impurity solver

### ISSUE THREAD

**Issue by Soumeniisc** [TRIQS/cthyb_matrix#4]
Dear Sir,

I installed Triqs tools(You helped me in ICTS conference). I have been trying to install HYB-IMPURITY SOLVER. I build the Impurity solver correctly. But it showing some problem during make (command).

It's showing  following error.....

" /home/soumen/IPURITY_SOLVER/build/python/wrap_cthyb_matrix_by_cython.cpp:11449:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings] "

I am attaching files 1> terminal error.txt  2>cmakecatche.txt

System Information:

GCC compiler=4.8.1
TRiQS library=1.0.0
Impurity_Solver=1.0.0
Ubuntu=12.04
Cython=0.19.2
Python=2.7.3

Thanks,

**Comment by mferrero** [comment]
Hi! From your message I can see that the compilation actually worked fine. The conversion issue you are mentioning is only a warning, not an error. However, it seems that the tests are not passing. Can you show me the content of the following files in the builld directory:

<pre>test/single_site_bethe_output</pre>

and

<pre>test/single_site_bethe_output.err</pre>

Thanks!

**Comment by Soumeniisc** [comment]
Hi!
single_site_bethe_output content nothing
single_site_bethe_output.err content:

Traceback (most recent call last):
  File "<stdin>", line 23, in <module>
ImportError: No module named pytriqs.archive

thanks

**Comment by mferrero** [comment]
I see. It looks like the module has difficulties to find TRIQS. I think you might have written the path to the TRIQS_PATH using the ~ symbol instead of using a full path. Can you try to completely erase your build directory, and start again but making sure you type:

<pre>cmake -DTRIQS_PATH=/home/soumen/install /home/soumen/IPURITY_SOLVER/sre</pre>

**Comment by mferrero** [comment]
If you want to attach outputs, the best is to put them in gist: https://gist.github.com/ and to give the link to your files here.

**Comment by Soumeniisc** [comment]
Hi!
first i tried with ...cmake -DTRIQS_PATH=/home/soumen/install /home/soumen/IPURITY_SOLVER/sre
this time during make it's showing:
/bin/sh: 1: /usr/bin/cython: not found
...........
Then I tried:
cmake -DCYTHON_EXECUTABLE=/usr/local/bin/cython -DTRIQS_PATH=/home/soumen/install /home/soumen/IPURITY_SOLVER/sre
this time i am getting the previous warning but 'make test' worked 
I am attaching link for single_site_bethe information:
https://gist.github.com/Soumeniisc/09b56ef680af2a5bee8f

Is it every thing fine???

Very very thanks

**Comment by mferrero** [comment]
Everything works! Great!
