### ISSUE TITLE
Measuring a non-diagonal Green's function when hybridization is diagonal

### ISSUE THREAD

**Issue by krivenko** [TRIQS/cthyb_matrix#5]
Good afternoon,

I have a question which is rather about CT-HYB algorithms in general. But probably this question may be considered as an improvement/feature request.
So let's imagine a CT-HYB simulation where the local problem is a dimer with a non-zero hopping matrix element between the atoms (t_{12} != 0). Each of the atoms has its own bath. In this formulation Delta_{12} = 0.

Now I have 3 questions to ask:
1) Is G_{12} zero?
2) Can G_{12} be measured in such a run, if we expand w.r.t. to diagonal Delta?
3) Can G_{12} be measured if we include t_{12} as a non-diagonal part of Delta?

From a test run of cthyb_matrix (https://gist.github.com/krivenko/8668853) I see that answers to questions 2 and 3 are 'No'. Which is very surprising provided that the answer to the first question should also be 'No'.

Could you comment on this issue?

**Comment by parcollet** [comment]
Hi Igor, 
It is even more general than cthyb.
You are trying to compute Z[Delta](using a QMC, but that is not essential here),
and G_12 = \partial Z / \partial Delta_12.
The pb is that your algorithm only compute on the sub-manifold Delta_12=0 
so there is no way to compute this derivative which is outside of the manifold (orthogonal to it).
You need a method that computes for all Delta, not just on the manifold.
So yes, G_12 is not zero, but the method can not compute it...

**Comment by krivenko** [comment]
OK, I understand the conceptual issue.
But why can't it be circumvented by putting t_{12} into Delta? cthyb_matrix forcefully pulls t_{12} back to the local Hamiltonian. Why this behavior?

**Comment by parcollet** [comment]
Delta(omega) would not -> 0 at omega ->infty 
then Delta(tau) is not a regular function.

**Comment by krivenko** [comment]
Ah, I see now. Thank you!
